services:
  backend:
    build: .
    container_name: issues_backend
    # MODIFIED LINE BELOW: Removed --reload
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --log-level debug
    volumes:
      - .:/app
      - uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=issue_tracker
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379
    expose:
      - "8000"

  # ... (rest of your services remain the same) ...

  db:
    image: postgres:15
    container_name: issues_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: issue_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: issues_redis
    restart: always
    expose:
      - "6379"

  worker:
    build: .
    container_name: issues_worker
    command: celery -A app.worker.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=issue_tracker
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379

  scheduler:
    build: .
    container_name: issues_scheduler
    command: celery -A app.worker.celery_app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=issue_tracker
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_URL=redis://redis:6379

  frontend: # Ensure this service is commented out or removed if you're running frontend locally
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: issues_frontend
    command: npm run dev -- --host 0.0.0.0 --port 5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    expose:
      - "5173"

  nginx:
    image: nginx:alpine
    container_name: issues_nginx
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend # Nginx still depends on frontend service, but frontend is stopped if running locally

volumes:
  postgres_data:
  uploads: